# Generated by Django 2.1.5 on 2019-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offense_name', models.CharField(max_length=100)),
                ('effective_from', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferencedActSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('act_name', models.CharField(max_length=100)),
                ('section', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='offence',
            name='referenced_acts',
            field=models.ManyToManyField(to='api.ReferencedActSection'),
        ),
    ]
