# Generated by Django 2.1.5 on 2019-02-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offence',
            old_name='offense_name',
            new_name='offence_name',
        ),
        migrations.AlterField(
            model_name='offence',
            name='referenced_acts',
            field=models.ManyToManyField(blank=True, to='api.ReferencedActSection'),
        ),
    ]
