# Generated by Django 2.1.5 on 2019-02-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190205_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='offence_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='referencedactsection',
            name='act_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
